icon_paths = {
                'txt': 'ui/images/icons/txt_icon.png',
                'doc': 'ui/images/icons/word_icon.png',
                'docx': 'ui/images/icons/docx_icon.png',
                'xls': 'ui/images/icons/xls_icon.png',
                'xlsx': 'ui/images/icons/xlxs_icon.png',
                'ppt': 'ui/images/icons/ppt_icon.png',
                'pptx': 'ui/images/icons/pptx_icon.png',
                'jpeg': 'ui/images/icons/jpeg_icon.png',
                'jpg': 'ui/images/icons/image_icon.png',
                'gif': 'ui/images/icons/image_icon.png',
                'png': 'ui/images/icons/png_icon.png',
                'mp3': 'ui/images/icons/music_icon.png',
                'mp4': 'ui/images/icons/video_icon.png',
                'pdf': 'ui/images/icons/pdf_icon.png',
                'py': 'ui/images/icons/python_icon.png',
                'html': 'ui/images/icons/html_icon.png',
                'js': 'ui/images/icons/js_icon.png',
                'java': 'ui/images/icons/java_icon.png',
                'json': 'ui/images/icons/json_icon.png',
                'cpp': 'ui/images/icons/cpp_icon.png',
                'c': 'ui/images/icons/c_icon.png',
                'mov': 'ui/images/icons/mov_icon.png',
                'mkv': 'ui/images/icons/mkv_icon.png',
                'zip': 'ui/images/icons/zip_icon.png',
                'rar': 'ui/images/icons/rar_icon.png',
                'folder': 'ui/images/icons/folder_icon.png',
                'default': 'ui/images/icons/default_icon.svg',
                'css': 'ui/images/icons/css_icon.png',
                'remove': 'ui/images/icons/remove_icon.png',

                # ... add more mappings as needed
            }